mmap_xen: Update to bitflags 2.4.0
Clippy gives this warning currently:

error: &-masking with zero
   --> src/mmap_xen.rs:433:1
    |
433 | / bitflags! {
434 | |     /// Flags for the Xen mmap message.
435 | |     pub struct MmapXenFlags: u32 {
436 | |         /// Standard Unix memory mapping.
...   |
446 | |     }
447 | | }
    | |_^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#bad_bit_mask
    = note: `#[deny(clippy::bad_bit_mask)]` on by default
    = note: this error originates in the macro `__impl_bitflags` which comes from the expansion of the macro `bitflags` (in Nightly builds, run with -Z macro-backtrace for more info)

Fix it by switching to a newer version of bitflags.

Signed-off-by: Viresh Kumar <viresh.kumar@linaro.org>